apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2018-11-22T16:32:29Z","reason":"SucceededGetScale","message":"the
      HPA controller was able to get the target''s current scale"},{"type":"ScalingActive","status":"False","lastTransitionTime":"2018-11-22T16:33:00Z","reason":"FailedGetResourceMetric","message":"the
      HPA was unable to compute the replica count: unable to get metrics for resource
      cpu: unable to fetch metrics from resource metrics API: the server could not
      find the requested resource (get pods.metrics.k8s.io)"}]'
  creationTimestamp: 2018-11-22T16:31:59Z
  name: backend-deployment
  namespace: default
  resourceVersion: "57023"
  selfLink: /apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/backend-deployment
  uid: 22a34436-ee74-11e8-87fe-00155d00033f
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: backend-deployment
  targetCPUUtilizationPercentage: 10

